# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerlinks',
            name='_name',
            field=models.CharField(blank=True, help_text="If left empty, the target's title will be used.", max_length=255, null=True, verbose_name='Alt. name'),
        ),
        migrations.AddField(
            model_name='headerlinks',
            name='show_participate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='headerlinks',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Page'),
        ),
    ]
