# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170130_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headerlinks',
            old_name='_name',
            new_name='participate_alt_name',
        ),
        migrations.RenameField(
            model_name='headerlinks',
            old_name='target',
            new_name='participate_target',
        ),
    ]
