# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
        ('core', '0003_auto_20170130_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerlinks',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='headerlinks',
            name='banner_intro_first',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headerlinks',
            name='banner_intro_second',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
