# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170130_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headerlinks',
            old_name='banner_intro_first',
            new_name='banner_first_intro',
        ),
        migrations.RenameField(
            model_name='headerlinks',
            old_name='banner_intro_second',
            new_name='banner_second_intro',
        ),
    ]
