# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_timeline_timelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='title',
            field=models.CharField(default='title', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelineitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
