# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import impacts_world.contrib.blocks
import impacts_world.core.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.wagtailcore.fields.StreamField((('timeline', wagtail.wagtailcore.blocks.StructBlock((('snippet', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(impacts_world.core.models.TimelineSnippet)),))), ('rich_text', impacts_world.contrib.blocks.RichTextBlock()), ('teaser', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=True))))), ('video_teaser', wagtail.wagtailcore.blocks.StructBlock((('video', wagtail.wagtailembeds.blocks.EmbedBlock(required=True)), ('text', wagtail.wagtailcore.blocks.RichTextBlock(required=True))))), ('challenge', wagtail.wagtailcore.blocks.StructBlock((('intro', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('challenge1', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True)), ('challenge2', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True)), ('challenge3', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True)), ('challenge4', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True))))), ('testimonial', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('institute', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('picture', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('testimonial', wagtail.wagtailcore.blocks.TextBlock(required=True)))), icon='openquote', template='blocks/testimonials_block.html'))), blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.wagtailcore.fields.StreamField((('timeline', wagtail.wagtailcore.blocks.StructBlock((('snippet', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(impacts_world.core.models.TimelineSnippet)),))), ('rich_text', impacts_world.contrib.blocks.RichTextBlock()), ('teaser', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=True))))), ('video_teaser', wagtail.wagtailcore.blocks.StructBlock((('video', wagtail.wagtailembeds.blocks.EmbedBlock(required=True)), ('text', wagtail.wagtailcore.blocks.RichTextBlock(required=True))))), ('challenge', wagtail.wagtailcore.blocks.StructBlock((('intro', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('challenge1', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True)), ('challenge2', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True)), ('challenge3', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True)), ('challenge4', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True))))), ('testimonial', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('institute', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('picture', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('testimonial', wagtail.wagtailcore.blocks.TextBlock(required=True)))), icon='openquote', template='blocks/testimonials_block.html'))), blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
