# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:52
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='members',
            new_name='members1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='members2',
            field=wagtail.wagtailcore.fields.RichTextField(default='first'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='members3',
            field=wagtail.wagtailcore.fields.RichTextField(default='first'),
            preserve_default=False,
        ),
    ]
