# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 10:42
from __future__ import unicode_literals

from django.db import migrations
import impacts_world.contrib.blocks
import impacts_world.core.models
import impacts_world.pages.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('timeline', wagtail.wagtailcore.blocks.StructBlock((('snippet', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(impacts_world.core.models.TimelineSnippet)),))), ('rich_text', impacts_world.contrib.blocks.RichTextBlock()), ('teaser', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=True))))), ('video_teaser', wagtail.wagtailcore.blocks.StructBlock((('video', wagtail.wagtailembeds.blocks.EmbedBlock(required=True)), ('text', wagtail.wagtailcore.blocks.RichTextBlock(required=True))))), ('challenge', wagtail.wagtailcore.blocks.StructBlock((('intro', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('challenge1', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True)), ('challenge2', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True)), ('challenge3', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True)), ('challenge4', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True))))), ('testimonials', wagtail.wagtailcore.blocks.StructBlock((('testimonials', wagtail.wagtailcore.blocks.ListBlock(impacts_world.pages.blocks.Testimonial)),)))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('timeline', wagtail.wagtailcore.blocks.StructBlock((('snippet', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(impacts_world.core.models.TimelineSnippet)),))), ('rich_text', impacts_world.contrib.blocks.RichTextBlock()), ('teaser', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=True))))), ('video_teaser', wagtail.wagtailcore.blocks.StructBlock((('video', wagtail.wagtailembeds.blocks.EmbedBlock(required=True)), ('text', wagtail.wagtailcore.blocks.RichTextBlock(required=True))))), ('challenge', wagtail.wagtailcore.blocks.StructBlock((('intro', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('challenge1', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True)), ('challenge2', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True)), ('challenge3', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True)), ('challenge4', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))), required=True))))), ('testimonials', wagtail.wagtailcore.blocks.StructBlock((('testimonials', wagtail.wagtailcore.blocks.ListBlock(impacts_world.pages.blocks.Testimonial)),)))), blank=True, null=True),
        ),
    ]
