# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 13:18
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170104_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='timeline',
            field=wagtail.wagtailcore.fields.StreamField((('event', wagtail.wagtailcore.blocks.StructBlock((('date', wagtail.wagtailcore.blocks.DateBlock(required=True)), ('text', wagtail.wagtailcore.blocks.RichTextBlock())))),)),
        ),
    ]
