# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170221_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformsubmission',
            name='identifier',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formfield',
            name='choices',
            field=models.TextField(blank=True, help_text='Semicolon separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices'),
        ),
    ]
