# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20170301_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='confirmation_email_text',
            field=wagtail.wagtailcore.fields.RichTextField(default='The form was submitted successfully. We will get back to you soon.'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='send_confirmation_email',
            field=models.BooleanField(default=False, verbose_name='Send confirmation email'),
        ),
    ]
