# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 14:07
from __future__ import unicode_literals

from django.db import migrations
import impacts_world.core.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_genericpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='first_intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='members1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='members2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='members3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='newsletter',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='plenary',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='second_intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='thank_you_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='to_address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='topic1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='topic2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='topic3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='topic4',
        ),
        migrations.AddField(
            model_name='genericpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('timeline', wagtail.wagtailcore.blocks.StructBlock((('snippet', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(impacts_world.core.models.TimelineSnippet)),))),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('timeline', wagtail.wagtailcore.blocks.StructBlock((('snippet', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(impacts_world.core.models.TimelineSnippet)),))),), blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
