# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170425_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='confirmation_email_subject',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Confirmation email subject'),
        ),
    ]
