# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 17:06
from __future__ import unicode_literals

from django.db import migrations
import impacts_world.contrib.blocks
import impacts_world.core.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20170130_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('timeline', wagtail.wagtailcore.blocks.StructBlock((('snippet', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(impacts_world.core.models.TimelineSnippet)),))), ('rich_text', impacts_world.contrib.blocks.RichTextBlock()), ('teaser', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('page', wagtail.wagtailcore.blocks.PageChooserBlock())))), ('challenge', wagtail.wagtailcore.blocks.StructBlock((('intro', wagtail.wagtailcore.blocks.RichTextBlock()), ('challenge1', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))))), ('challenge2', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))))), ('challenge3', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))))), ('challenge4', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))))))))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('timeline', wagtail.wagtailcore.blocks.StructBlock((('snippet', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(impacts_world.core.models.TimelineSnippet)),))), ('rich_text', impacts_world.contrib.blocks.RichTextBlock()), ('teaser', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('page', wagtail.wagtailcore.blocks.PageChooserBlock())))), ('challenge', wagtail.wagtailcore.blocks.StructBlock((('intro', wagtail.wagtailcore.blocks.RichTextBlock()), ('challenge1', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))))), ('challenge2', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))))), ('challenge3', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))))), ('challenge4', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('short_description', impacts_world.contrib.blocks.RichTextBlock(required=True))))))))), blank=True, null=True),
        ),
    ]
