# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_formpage_confirmation_email_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time')], max_length=16, verbose_name='field type'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='confirmation_email_text',
            field=models.TextField(blank=True, default='The form was submitted successfully. We will get back to you soon.', null=True),
        ),
    ]
