# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20170206_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='bottom_content',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='top_content',
        ),
        migrations.AddField(
            model_name='formpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time')], max_length=16, verbose_name='field type'),
        ),
    ]
