# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pages', '0012_formpage_form_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='timeline_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.TimelineSnippet'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='confirmation_text',
            field=wagtail.wagtailcore.fields.RichTextField(default='The form was submitted successfully. We will get back to you soon.'),
        ),
    ]
