# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_timelinepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plenaryoverviewpage',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='plenaryoverviewpage',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='plenaryoverviewpage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='posteroverviewpage',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='posteroverviewpage',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='posteroverviewpage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='workshopoverviewpage',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='workshopoverviewpage',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='workshopoverviewpage',
            name='room',
        ),
    ]
