# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_personsnippet'),
        ('pages', '0018_auto_20170207_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plenaryitempage',
            old_name='intro',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='posteritempage',
            old_name='intro',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='workshopitempage',
            old_name='intro',
            new_name='description',
        ),
        migrations.AddField(
            model_name='workshopitempage',
            name='convenor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.PersonSnippet'),
        ),
    ]
