# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import impacts_world.pages.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170207_1252'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('pages', '0018_auto_20170207_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOverviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('content', wagtail.wagtailcore.fields.StreamField((('day_list', wagtail.wagtailcore.blocks.ListBlock(impacts_world.pages.blocks.DayBlock, template='blocks/day-list-block.html')),), blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='posterchallengepage',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='posterchallengepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='timelinepage',
            name='page_ptr',
        ),
        migrations.RenameField(
            model_name='plenaryitempage',
            old_name='intro',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='posteritempage',
            old_name='intro',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='workshopitempage',
            old_name='intro',
            new_name='description',
        ),
        migrations.AddField(
            model_name='plenaryitempage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('plenary_list', wagtail.wagtailcore.blocks.ListBlock(impacts_world.pages.blocks.KeynoteBlock, icon='password', label='Keynotes', template='blocks/keynote-list-block.html')),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopitempage',
            name='convenor_institute',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workshopitempage',
            name='convenor_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='PosterChallengePage',
        ),
        migrations.DeleteModel(
            name='TimelinePage',
        ),
    ]
