# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20170213_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshopchallengepage',
            old_name='intro',
            new_name='description',
        ),
    ]
