# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20170207_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopitempage',
            name='convenor',
        ),
        migrations.AddField(
            model_name='workshopitempage',
            name='convenor_institute',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workshopitempage',
            name='convenor_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
