# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 14:36
from __future__ import unicode_literals

from django.db import migrations
import impacts_world.pages.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20170213_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopitempage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('contribution_list', wagtail.wagtailcore.blocks.ListBlock(impacts_world.pages.blocks.ContributionBlock, icon='password', label='Contributions')),), blank=True, null=True),
        ),
    ]
