# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('core', '0003_auto_20170207_1252'),
        ('pages', '0020_auto_20170207_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posterchallengepage',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='posterchallengepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='PosterChallengePage',
        ),
    ]
