# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 13:38
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20170207_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinepage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
