# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import impacts_world.pages.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_workshopitempage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteritempage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('contribution_list', wagtail.wagtailcore.blocks.ListBlock(impacts_world.pages.blocks.PosterBlock, icon='doc-full', label='Posters', template='blocks/list-block.html')),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plenaryitempage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('plenary_list', wagtail.wagtailcore.blocks.ListBlock(impacts_world.pages.blocks.KeynoteBlock, icon='password', label='Keynotes', template='blocks/list-block.html')),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posteritempage',
            name='room',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workshopitempage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('contribution_list', wagtail.wagtailcore.blocks.ListBlock(impacts_world.pages.blocks.ContributionBlock, icon='doc-full', label='Contributions', template='blocks/list-block.html')),), blank=True, null=True),
        ),
    ]
