# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import impacts_world.contrib.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('core', '0003_auto_20170207_1252'),
        ('pages', '0022_timelinepage_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('content', wagtail.wagtailcore.fields.StreamField((('plenary', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('time', wagtail.wagtailcore.blocks.TimeBlock(required=True)), ('description', impacts_world.contrib.blocks.RichTextBlock(required=False))))), ('workshop', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('time', wagtail.wagtailcore.blocks.TimeBlock(required=True)), ('description', impacts_world.contrib.blocks.RichTextBlock(required=False))))), ('poster', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('time', wagtail.wagtailcore.blocks.TimeBlock(required=True)), ('description', impacts_world.contrib.blocks.RichTextBlock(required=False))))), ('special_event', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('time', wagtail.wagtailcore.blocks.TimeBlock(required=True)), ('description', impacts_world.contrib.blocks.RichTextBlock(required=False)))))), blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='timelinepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='TimelinePage',
        ),
    ]
