# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20170213_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteritempage',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
