# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 09:19
from __future__ import unicode_literals

from django.db import migrations
import impacts_world.pages.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20170207_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('day_list', wagtail.wagtailcore.blocks.ListBlock(impacts_world.pages.blocks.DayBlock)),), blank=True, null=True),
        ),
    ]
