# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 16:56
from __future__ import unicode_literals

from django.db import migrations
import impacts_world.pages.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20170213_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteritempage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('contribution_list', wagtail.wagtailcore.blocks.ListBlock(impacts_world.pages.blocks.PosterContributionBlock, icon='doc-full', label='Posters', template='blocks/list-block.html')),), blank=True, null=True),
        ),
    ]
