# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 17:13
from __future__ import unicode_literals

from django.db import migrations
import impacts_world.contrib.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20170213_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plenaryitempage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('keynote', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('description', impacts_world.contrib.blocks.RichTextBlock(required=True)), ('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('institute', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('picture', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True))))),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posteritempage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('contribution', wagtail.wagtailcore.blocks.StructBlock((('number', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('authors', impacts_world.contrib.blocks.RichTextBlock(required=True)), ('description', impacts_world.contrib.blocks.RichTextBlock(required=True))))),), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshopitempage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('contribution', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('institute', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('description', impacts_world.contrib.blocks.RichTextBlock(required=True))))),), blank=True, null=True),
        ),
    ]
