# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
        ('pages', '0025_auto_20170213_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshopchallengepage',
            old_name='icon',
            new_name='challenge_icon',
        ),
        migrations.AddField(
            model_name='workshopchallengepage',
            name='workshop_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
