# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20170208_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgrammePage',
            new_name='ProgramOverviewPage',
        ),
    ]
