# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 11:32
from __future__ import unicode_literals

from django.db import migrations
import impacts_world.pages.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20170208_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='plenaryitempage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('day_list', wagtail.wagtailcore.blocks.ListBlock(impacts_world.pages.blocks.PlenaryBlock, template='blocks/plenary-list-block.html')),), blank=True, null=True),
        ),
    ]
