# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 12:32
from __future__ import unicode_literals

from django.db import migrations
import impacts_world.contrib.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20170214_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programoverviewpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('day', wagtail.wagtailcore.blocks.StructBlock((('date', wagtail.wagtailcore.blocks.DateBlock(classname='date-field', required=True)), ('title', wagtail.wagtailcore.blocks.CharBlock(classname='title-field', required=True)), ('panels', wagtail.wagtailcore.blocks.StreamBlock((('refreshment', wagtail.wagtailcore.blocks.StructBlock((('time', wagtail.wagtailcore.blocks.TimeBlock(classname='time-field', required=True)), ('title', wagtail.wagtailcore.blocks.CharBlock(classname='title-field', required=True)), ('description', impacts_world.contrib.blocks.RichTextBlock(required=False))))), ('plenary', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(classname='title-field', help_text='If empty automatically uses title of linked plenary page.', required=False)), ('description', impacts_world.contrib.blocks.RichTextBlock(required=False)), ('plenary_page', wagtail.wagtailcore.blocks.PageChooserBlock(required=True, target_model='pages.PlenaryItemPage'))))), ('workshop', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(classname='title-field', required=True)), ('description', impacts_world.contrib.blocks.RichTextBlock(required=False)), ('workshop_page', wagtail.wagtailcore.blocks.PageChooserBlock(required=True, target_model='pages.WorkshopItemPage'))))), ('poster', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(classname='title-field', required=True)), ('description', impacts_world.contrib.blocks.RichTextBlock(required=False)), ('poster_page', wagtail.wagtailcore.blocks.PageChooserBlock(required=True, target_model='pages.PosterItemPage'))))), ('special_event', wagtail.wagtailcore.blocks.StructBlock((('time', wagtail.wagtailcore.blocks.TimeBlock(classname='time-field', required=True)), ('title', wagtail.wagtailcore.blocks.CharBlock(classname='title-field', required=True)), ('description', impacts_world.contrib.blocks.RichTextBlock(required=False))))))))))),), blank=True, null=True),
        ),
    ]
