# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 11:35
from __future__ import unicode_literals

from django.db import migrations
import impacts_world.pages.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_plenaryitempage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plenaryitempage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('plenary_list', wagtail.wagtailcore.blocks.ListBlock(impacts_world.pages.blocks.KeynoteBlock, icon='list-ul', label='Plenaries', template='blocks/plenary-list-block.html')),), blank=True, null=True),
        ),
    ]
