# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_customformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Max length for single and multiline input fields.', null=True, verbose_name='max length'),
        ),
    ]
